title: Екатерина Вишнякова
theme: jekyll-theme-tactile
plugins:
  - jekyll-responsive-image
responsive_image:
  template: _includes/imager-js.html
  sizes:
    - width: 320
    - width: 480
    - width: 800
